### ISSUE TITLE
Link to Rahul's github page is incorrect

### ISSUE THREAD

**Issue by nirban256** [Cyfrin/audit-checklist#26]
On clicking the profile page link of **Rahul** which is at number starting from the last it shows the following error

![image](https://github.com/Cyfrin/audit-checklist/assets/74231771/91839c40-1eb8-40dc-933f-5ae10d8f8fa9)

Please fix the issue or give me the correct link and I can fix it.

**Comment by hans-cyfrin** [comment]
Fixed. Thanks for pointing it out.
